name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        otp-version: [25, 26, 27]
    runs-on: ${{ matrix.platform }}
    container:
      image: erlang:${{ matrix.otp-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: rebar3 compile
    - name: Run EUnit Tests
      run: rebar3 eunit --cover
    - name: Run Common Tests
      run: rebar3 ct
    - name: Check app calls
      run: rebar3 check_app_calls
    - name: Create Cover Reports
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: rebar3 cover
    - name: Produce Documentation
      run: rebar3 ex_doc
    - name: Publish Documentation
      uses: actions/upload-artifact@v4
      with:
        name: edoc ${{ matrix.otp-version }}
        path: doc
    - name: Upload Common Test result
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Common Test ${{ matrix.otp-version }}
        path: _build/test/logs/**
        retention-days: 3
